[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "svmm"
version = "0.1.0"
description = "Simple/small virtual machine manager built on libvirt and cloud-init"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
dependencies = ["pyyaml", "argcomplete>=3.0"]

[project.scripts]
svmm = "svmm.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["svmm*"]

